language: java

jdk:
  - openjdk11

# cache:
#   directories:
#     - '$HOME/.m2/repository'

  #before_install:
  # - chmod +x gradlew

script:
  - mvn clean verify

#  after_success:
#    - cd ./target
#    - git init
#    - git config user.name "squall1744"
#    - git config user.email "squall1744@163.com"
#    - git add spring-boot-jsp.war
#    - git commit -m "version 1"
#    - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
#
#  branches:
#    only:
#      - test
#
#  notifications:
#    email: false

